local calendar_model = require('agenda.model.entity.calendar')

describe('Calendar model', function()
    before_each(function()
        calendar_model:close()
    end)

    describe('open', function()
        it('initializes from a timestamp', function()
            -- 2026-02-11 14:30:00
            local ts = os.time({ year = 2026, month = 2, day = 11, hour = 14, min = 30, sec = 0 })
            local cb = function() end
            calendar_model:open(ts, cb)

            assert.are.equal(2026, calendar_model:get_year())
            assert.are.equal(2, calendar_model:get_month())
            assert.are.equal(11, calendar_model:get_day())
            assert.are.equal(14, calendar_model:get_hour())
            assert.are.equal(30, calendar_model:get_minute())
            assert.are.equal("day", calendar_model:get_active_field())
            assert.is_true(calendar_model:is_active())
        end)

        it('defaults to now when timestamp is nil', function()
            local cb = function() end
            calendar_model:open(nil, cb)

            local now = os.date("*t")
            assert.are.equal(now.year, calendar_model:get_year())
            assert.are.equal(now.month, calendar_model:get_month())
            assert.is_true(calendar_model:is_active())
        end)
    end)

    describe('close', function()
        it('resets all state', function()
            local ts = os.time({ year = 2026, month = 6, day = 15, hour = 10, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:close()

            assert.are.equal(0, calendar_model:get_year())
            assert.are.equal(0, calendar_model:get_month())
            assert.are.equal(0, calendar_model:get_day())
            assert.are.equal("day", calendar_model:get_active_field())
            assert.is_false(calendar_model:is_active())
            assert.is_nil(calendar_model:get_callback())
        end)
    end)

    describe('day navigation', function()
        before_each(function()
            -- Start on Feb 15 2026
            local ts = os.time({ year = 2026, month = 2, day = 15, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
        end)

        it('next_day increments day', function()
            calendar_model:next_day()
            assert.are.equal(16, calendar_model:get_day())
        end)

        it('prev_day decrements day', function()
            calendar_model:prev_day()
            assert.are.equal(14, calendar_model:get_day())
        end)

        it('next_day does not go past end of month', function()
            -- Feb 2026 has 28 days
            local ts = os.time({ year = 2026, month = 2, day = 28, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:next_day()
            assert.are.equal(28, calendar_model:get_day())
        end)

        it('prev_day does not go below 1', function()
            local ts = os.time({ year = 2026, month = 2, day = 1, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:prev_day()
            assert.are.equal(1, calendar_model:get_day())
        end)
    end)

    describe('week navigation', function()
        before_each(function()
            local ts = os.time({ year = 2026, month = 2, day = 15, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
        end)

        it('next_week adds 7 days', function()
            calendar_model:next_week()
            assert.are.equal(22, calendar_model:get_day())
        end)

        it('prev_week subtracts 7 days', function()
            calendar_model:prev_week()
            assert.are.equal(8, calendar_model:get_day())
        end)

        it('next_week does not exceed month', function()
            local ts = os.time({ year = 2026, month = 2, day = 25, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:next_week()
            -- 25 + 7 = 32, but Feb has 28 days, so stays at 25
            assert.are.equal(25, calendar_model:get_day())
        end)

        it('prev_week does not go below 1', function()
            local ts = os.time({ year = 2026, month = 2, day = 5, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:prev_week()
            -- 5 - 7 = -2, stays at 5
            assert.are.equal(5, calendar_model:get_day())
        end)
    end)

    describe('month navigation', function()
        it('next_month increments month', function()
            local ts = os.time({ year = 2026, month = 2, day = 15, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:next_month()
            assert.are.equal(3, calendar_model:get_month())
            assert.are.equal(15, calendar_model:get_day())
        end)

        it('prev_month decrements month', function()
            local ts = os.time({ year = 2026, month = 2, day = 15, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:prev_month()
            assert.are.equal(1, calendar_model:get_month())
            assert.are.equal(15, calendar_model:get_day())
        end)

        it('next_month wraps year', function()
            local ts = os.time({ year = 2026, month = 12, day = 15, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:next_month()
            assert.are.equal(1, calendar_model:get_month())
            assert.are.equal(2027, calendar_model:get_year())
        end)

        it('prev_month wraps year', function()
            local ts = os.time({ year = 2026, month = 1, day = 15, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:prev_month()
            assert.are.equal(12, calendar_model:get_month())
            assert.are.equal(2025, calendar_model:get_year())
        end)

        it('clamps day when month has fewer days', function()
            -- Jan 31 -> Feb (28 days)
            local ts = os.time({ year = 2026, month = 1, day = 31, hour = 12, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:next_month()
            assert.are.equal(2, calendar_model:get_month())
            assert.are.equal(28, calendar_model:get_day())
        end)
    end)

    describe('time editing', function()
        before_each(function()
            local ts = os.time({ year = 2026, month = 2, day = 15, hour = 14, min = 30, sec = 0 })
            calendar_model:open(ts, function() end)
        end)

        it('increment_hour wraps at 24', function()
            local ts = os.time({ year = 2026, month = 2, day = 15, hour = 23, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:increment_hour()
            assert.are.equal(0, calendar_model:get_hour())
        end)

        it('decrement_hour wraps at 0', function()
            local ts = os.time({ year = 2026, month = 2, day = 15, hour = 0, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:decrement_hour()
            assert.are.equal(23, calendar_model:get_hour())
        end)

        it('increment_minute adds 5', function()
            calendar_model:increment_minute()
            assert.are.equal(35, calendar_model:get_minute())
        end)

        it('decrement_minute subtracts 5', function()
            calendar_model:decrement_minute()
            assert.are.equal(25, calendar_model:get_minute())
        end)

        it('increment_minute wraps at 60', function()
            local ts = os.time({ year = 2026, month = 2, day = 15, hour = 14, min = 55, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:increment_minute()
            assert.are.equal(0, calendar_model:get_minute())
        end)

        it('decrement_minute wraps at 0', function()
            local ts = os.time({ year = 2026, month = 2, day = 15, hour = 14, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            calendar_model:decrement_minute()
            assert.are.equal(55, calendar_model:get_minute())
        end)
    end)

    describe('toggle_field', function()
        it('toggles between day and time', function()
            calendar_model:open(os.time(), function() end)
            assert.are.equal("day", calendar_model:get_active_field())
            calendar_model:toggle_field()
            assert.are.equal("time", calendar_model:get_active_field())
            calendar_model:toggle_field()
            assert.are.equal("day", calendar_model:get_active_field())
        end)
    end)

    describe('get_timestamp', function()
        it('builds correct timestamp from current state', function()
            local ts = os.time({ year = 2026, month = 6, day = 15, hour = 10, min = 30, sec = 0 })
            calendar_model:open(ts, function() end)

            local result = calendar_model:get_timestamp()
            local t = os.date("*t", result)
            assert.are.equal(2026, t.year)
            assert.are.equal(6, t.month)
            assert.are.equal(15, t.day)
            assert.are.equal(10, t.hour)
            assert.are.equal(30, t.min)
        end)
    end)

    describe('get_month_data', function()
        it('returns correct data for February 2026', function()
            local ts = os.time({ year = 2026, month = 2, day = 1, hour = 0, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)

            local data = calendar_model:get_month_data()
            assert.are.equal(28, data.days_in_month)
            -- Feb 1, 2026 is a Sunday -> monday-based = 7
            assert.are.equal(7, data.first_weekday)
        end)

        it('returns correct data for March 2026', function()
            local ts = os.time({ year = 2026, month = 3, day = 1, hour = 0, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)

            local data = calendar_model:get_month_data()
            assert.are.equal(31, data.days_in_month)
            -- March 1, 2026 is a Sunday -> monday-based = 7
            assert.are.equal(7, data.first_weekday)
        end)
    end)

    describe('days_in_month', function()
        it('handles leap year', function()
            local ts = os.time({ year = 2024, month = 2, day = 1, hour = 0, min = 0, sec = 0 })
            calendar_model:open(ts, function() end)
            assert.are.equal(29, calendar_model:days_in_month(2024, 2))
        end)

        it('handles non-leap year', function()
            assert.are.equal(28, calendar_model:days_in_month(2026, 2))
        end)

        it('handles months with 31 days', function()
            assert.are.equal(31, calendar_model:days_in_month(2026, 1))
            assert.are.equal(31, calendar_model:days_in_month(2026, 3))
            assert.are.equal(31, calendar_model:days_in_month(2026, 7))
        end)

        it('handles months with 30 days', function()
            assert.are.equal(30, calendar_model:days_in_month(2026, 4))
            assert.are.equal(30, calendar_model:days_in_month(2026, 6))
            assert.are.equal(30, calendar_model:days_in_month(2026, 9))
        end)
    end)
end)
